# Generated by Django 5.1.1 on 2024-09-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size', models.CharField(max_length=50)),
                ('operating_system', models.CharField(default='Mac', max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused')], default='stopped', max_length=20)),
            ],
        ),
    ]
